repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args:
          - --max-line-length=128
          - --ignore=E501,E402
          - --exclude=ui/*,resources_rc.py

  - repo: https://github.com/pre-commit/mirrors-pylint
    rev: v3.0.0a5
    hooks:
      - id: pylint
        args:
          - --max-line-length=128
          - --ignore=ui,visa_test.py,resources_rc.py
          - --ignore-paths=ui
          - --ignored-modules=os
          - --disable=E0401,C0103,W0703,R0801,R0902
          - --extension-pkg-whitelist=PySide6