repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args:
          - --max-line-length=128
          - --ignore=E501,E402
          - --exclude=ui/*,resources_rc.py